package Project.Common;

public enum PayloadType {
    CONNECT, DISCONNECT, MESSAGE, CREATE_ROOM, JOIN_ROOM, LIST_ROOMS, CLIENT_ID, SYNC_CLIENT, READY, PHASE, TURN,
    RESET_TURNS, RESET_READY, CURRENT_TURN, CHOICE, REMOVED, POINTS, AWAY
}
//zb64 4/8/24
